[project]
name = "python-fundamentals-fb"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "marimo>=0.23.3",
    "pandas",
    "numpy",
    "matplotlib",
    "mplfinance",
    "pytz",
    "python-dateutil",
    "requests",
]

[tool.ruff]
line-length = 88
target-version = "py312"

[tool.ruff.lint]
select = ["E", "F", "I"]
